name: build
on:
  - pull_request
  - push

jobs:
  build-ci-deploy:
    name: "Build and push ci-deploy"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Secrets can't be references in conditionals, so we copy it into an
    # environment variable
    env:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Login to DockerHub
        if: ${{ env.docker_username != '' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone project
        uses: actions/checkout@v2

      - name: Generate docker tags and labels
        id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: nejla/ci-deploy
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ci-deploy
          file: ci-deploy/Dockerfile
          push: ${{ env.docker_username != '' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

  build-nejla-build:
    name: "Build and push nejla-build"
    runs-on: ubuntu-latest
    env:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Login to DockerHub
        if: ${{ env.docker_username != '' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate docker tags and labels
        id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: nejla/nejla-build
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: nejla-build
          file: nejla-build/Dockerfile
          push: ${{ env.docker_username != '' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
